shared:
  support: contact@lovindevs.com
  support_mailbox: "David Boureau from lovindevs <contact@lovindevs.com>"
  notifications_mailbox: "lovindevs <notifications@lovindevs.com>"
  updates_mailbox: "lovindevs <updates@lovindevs.com>"
  reminders_mailbox: "lovindevs <reminders@lovindevs.com>"
