shared:
  support: joe@lovindevs.com
  support_mailbox: "Joe Masilotti from lovindevs <joe@lovindevs.com>"
  notifications_mailbox: "lovindevs <notifications@lovindevs.com>"
  updates_mailbox: "lovindevs <updates@lovindevs.com>"
  reminders_mailbox: "lovindevs <reminders@lovindevs.com>"
