shared:
  support: contact@jsdevs.com
  support_mailbox: "David Boureau from jsdevs <contact@jsdevs.com>"
  notifications_mailbox: "jsdevs <notifications@jsdevs.com>"
  updates_mailbox: "jsdevs <updates@jsdevs.com>"
  reminders_mailbox: "jsdevs <reminders@jsdevs.com>"
