shared:
  support: contact@jsdevs.co
  support_mailbox: "David Boureau from jsdevs <contact@jsdevs.co>"
  notifications_mailbox: "jsdevs <notifications@jsdevs.co>"
  updates_mailbox: "jsdevs <updates@jsdevs.co>"
  reminders_mailbox: "jsdevs <reminders@jsdevs.co>"
